<?php

$categories['twitter'] = array(
    'Book & Magazines' => array(
        'Book',
        'Publisher',
        'Bookshop',
        'Library',
        'Magazine',
        'Book Series',
        'News Paper',
    ),
    'Brands & Products' => array(
        'Product/Service',
        'Website',
        'Cars',
        'Bags/Luggage',
        'Camera/Photo',
        'Clothing',
        'Computers',
        'Software',
        'Office Supplies',
        'Electronics',
        'Health/Beauty',
        'Appliances',
        'Building Materials',
        'Commercial Equipment',
        'Home Décor',
        'Furniture',
        'Household Supplies',
        'Kitchen/Cooking',
        'Patio/Garden',
        'Tools/Equipment',
        'Wine/Spirits',
        'Jewelry/Watches',
        'Pet Supplies',
        'Baby Goods/Kids Goods',
        'Food/Beverages',
        'Vitamins/Supplements',
    ),
    'Companies & Organisations' => array(
        'Company',
        'Health/Beauty',
        'Media/News/Publishing',
        'Bank/Financial Institution',
        'Non-Governmental Organisation (NGO)',
        'Insurance Company',
        'Small Business',
        'Energy/Utility',
        'Retail and Consumer Merchandise',
        'Cars and Parts',
        'Industrials',
        'Transport/Freight',
        'Health/Medical/Pharmaceuticals',
        'Aerospace/Defense',
        'Mining/Materials',
        'Farming/Agricultural',
        'Chemicals',
        'Consulting/Business Services',
        'Legal/Law',
        'Education',
        'Engineering/Construction',
        'Food/Beverages',
        'Telecommunication',
        'Computers/Technology',
        'Internet/Software',
        'Travel/Leisure',
        'Community Organisation',
        'Political Organisation',
        'Church/Religious Organisation',
        'Organisation',
        'School',
        'University',
        'Non-Profit Organisation',
        'Government Organisation',
        'Cause',
        'Political Party',
        'Middle School',
        'Biotechnology',
        'Preschool',
        'Primary School',
    ),
    'Films' => array(
        'Film',
        'Producer',
        'Writer',
        'Studio',
        'Cinema',
        'TV/Film Award',
        'Fictional Character',
        'Film Character',
    ),
    'Local Business' => array(
        'Cinema',
        'Concert Venue',
        'Bookshop',
        'Library',
        'Lawyer',
        'Doctor',
        'Restaurant/Café',
        'Bar',
        'Club',
        'Outdoor Gear/Sporting Goods',
        'Education',
        'Church/Religious Organisation',
        'Local Business',
        'Hotel',
        'Landmark',
        'Airport',
        'Sports Venue',
        'Arts/Entertainment/Nightlife',
        'Vehicles',
        'Spas/Beauty/Personal Care',
        'Event Planning/Event Services',
        'Bank/Financial Services',
        'Food/Groceries',
        'Health/Medical/Pharmacy',
        'DIY',
        'Pet Services',
        'Professional Services',
        'Business Services',
        'Community/Government',
        'Property',
        'Shopping/Retail',
        'Public Places',
        'Attractions/Things to Do',
        'Sports/Recreation/Activities',
        'Tours/Sightseeing',
        'Transport/Freight',
        'Hospital/Clinic',
        'Museum/Art Gallery',
        'School',
        'University',
        'Middle School',
    ),
    'Music' => array(
        'Album',
        'Song',
        'Musician/Band',
        'Music Video',
        'Concert Tour',
        'Concert Venue',
        'Radio Station',
        'Record Label',
        'Music Award',
        'Music Chart',
    ),
    'Other' => array(
        'Community',
        'Just for fun',
        'Podcast',
    ),
    'People' => array(
        'Actor/Director',
        'Producer',
        'Writer',
        'Fictional Character',
        'Film Character',
        'Musician/Band',
        'Author',
        'Sportsperson',
        'Artist',
        'Public Figure',
        'Journalist',
        'News Personality',
        'Chef',
        'Business Person',
        'Comedian',
        'Entertainer',
        'Teacher',
        'Dancer',
        'Designer',
        'Photographer',
        'Entrepreneur',
        'Politician',
        'Government Official',
        'Coach',
        'Pet Services',
        'Blogger',
        'Scientist',
    ),
    'Sports' => array(
        'Sportsperson',
        'Sports League',
        'Sports Team',
        'Coach',
        'Amateur Sports Team',
        'School Sports Team',
        'Sports Event',
        'Sports Venue',
    ),
    'Television' => array(
        'Writer',
        'Studio',
        'TV/Film Award',
        'Fictional Character',
        'TV Programme',
        'TV Network',
        'TV Channel',
        'Episode',
        'TV Series',
    ),
    'Websites & Blogs' => array(
        'Personal Blog',
        'Arts/Humanities Website',
        'Business/Economy Website',
        'Computers/Internet Website',
        'Education Website',
        'Entertainment Website',
        'Government Website',
        'Health/Wellness Website',
        'Home/Garden Website',
        'News/Media Website',
        'Recreation/Sports Website',
        'Reference Website',
        'Regional Website',
        'Science Website',
        'Society/Culture Website',
        'Local/Travel Website',
        'Teens/Kids Website',
        'Personal Website',
    ),
);

$categories['facebook'] = array(
    'Airport',
    'Arts/Entertainment/Nightlife',
    'Baby Goods/Kids Goods',
    'Bank/Financial Services',
    'Bar',
    'Bookshop',
    'Building Materials',
    'Camera/Photo',
    'Church/Religious Organisation',
    'Cinema',
    'Clothing',
    'Club',
    'Commercial Equipment',
    'DIY',
    'Doctor',
    'Education',
    'Electronics',
    'Event Planning/Event Services',
    'Food/Beverages',
    'Food/Groceries',
    'Furniture',
    'Health/Beauty',
    'Health/Medical/Pharmacy',
    'Home Décor',
    'Hospital/Clinic',
    'Hotel',
    'Household Supplies',
    'Jewelry/Watches',
    'Kitchen/Cooking',
    'Lawyer',
    'Library',
    'Museum/Art Gallery',
    'Office Supplies',
    'Outdoor Gear/Sporting Goods',
    'Patio/Garden',
    'Pet Services',
    'Professional Services',
    'Restaurant/Café',
    'Shopping/Retail',
    'Software',
    'Sports/Recreation/Activities',
    'Tours/Sightseeing',
    'Transport/Freight',
    'Vehicles',
    'Vitamins/Supplements',
    'Wine/Spirits',
);

return $categories;